# Generated by Django 5.0.6 on 2024-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed at')),
                ('status', models.CharField(choices=[('active', 'Активно"'), ('blocked', 'Заблокировано')], default='new', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Guest Book',
                'verbose_name_plural': 'GuestBooks',
                'db_table': 'guestBook',
            },
        ),
    ]
